### ISSUE TITLE
Drop Python 3.8 & Add Support for Python 3.12

### ISSUE THREAD

**Issue by irtazaakram** [openedx/acid-block#184]
**Description:**

Follow and complete all of the following steps for the issue to be marked as done.

- [ ] Update the `tox.ini`, `setup.py`, `setup.cfg`, or `pyproject.toml` to remove Python 3.8 and add support for Python 3.12.
- [ ] Ensure GitHub Actions workflows, including the CI matrix, are updated to reflect the supported Python versions (3.11, and 3.12).
- [ ] Adjust any testing or build configurations to ensure compatibility with Python 3.12.
- [ ] Remove references to Python versions earlier than 3.11 from all relevant configuration files.
- [ ] Run all tests and verify they pass in the CI with the updated versions.
- [ ] Add a CHANGELOG entry: “Dropped support for Python 3.8 and added support for Python 3.12.”
- [ ] Bump the package version and release a new version on GitHub & PyPI (where applicable).

**Comment by ttqureshi** [comment]
@irtazaakram we are using python version 3.11.9 locally. Is it ok if we add support for 3.11 instead of 3.12?

<img width="745" alt="image" src="https://github.com/user-attachments/assets/a75eb29d-1d27-4dc4-b6ab-689766ffcf75">

**Comment by irtazaakram** [comment]
@ttqureshi We want to add support for both Python 3.11 and 3.12.

**Comment by ttqureshi** [comment]
okay
